name: Test Secrets

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Secrets
        run: |
          echo "Testing hardcoded values..."
          
          # Hardcoded values
          PROJECT_REF="nbjuhxzjgegjvigsstljy"
          ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ianVoeHpqZ2VnanZpZ3N0bGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjUwMzAsImV4cCI6MjA3MTQ0MTAzMH0.9ZGYw5f1_HYXftiymb7pZqrbM1-VFb2nATcSgOVkTec"
          URL="https://${PROJECT_REF}.supabase.co/functions/v1/send-reminders"
          
          echo "Project Ref: $PROJECT_REF"
          echo "URL: $URL"
          
          # Test the API call
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${ANON_KEY}" \
            -H "Content-Type: application/json" \
            -H "apikey: ${ANON_KEY}" \
            "${URL}")
          
          echo "Response: $response"
